M48
; DRILL file {KiCad 8.0.5} date 2025-02-24T01:44:16-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-24T01:44:16-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X1.6183Y-2.5499
T2
X1.5748Y-1.0236
X1.5748Y-3.189
X4.5276Y-1.0236
X4.5276Y-3.189
M30
